import bcrypt from 'bcryptjs';
import { User, Employee, Department, Attendance, LeaveRequest, PerformanceReview } from '../types.js';

// Pre-seeded Hash for "password123"
const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('password123', 10);

export const departments: Department[] = [
  {
    id: 'dept-1',
    departmentName: 'Engineering',
    description: 'Software development, cloud infrastructure, and AI engineering teams.',
    managerName: 'Alexander Vance',
    budget: 850000,
  },
  {
    id: 'dept-2',
    departmentName: 'Human Resources',
    description: 'Talent acquisition, employee welfare, payroll, and compliance.',
    managerName: 'Sarah Jenkins',
    budget: 350000,
  },
  {
    id: 'dept-3',
    departmentName: 'Product & Design',
    description: 'Product strategy, UX/UI research, and design systems.',
    managerName: 'Emily Watson',
    budget: 450000,
  },
  {
    id: 'dept-4',
    departmentName: 'Sales & Marketing',
    description: 'Enterprise sales, digital marketing, and growth partnerships.',
    managerName: 'Marcus Brody',
    budget: 620000,
  },
  {
    id: 'dept-5',
    departmentName: 'Finance & Legal',
    description: 'Corporate financial auditing, budget allocation, and legal compliance.',
    managerName: 'Victoria Sterling',
    budget: 520000,
  },
  {
    id: 'dept-6',
    departmentName: 'Operations & IT',
    description: 'DevOps infrastructure, IT support, facilities, and vendor management.',
    managerName: 'Robert Taylor',
    budget: 410000,
  },
];

export const employees: Employee[] = [
  {
    id: 'emp-1',
    userId: 'usr-1',
    fullName: 'Alexander Vance',
    email: 'admin@enterprise.com',
    phone: '+1 (555) 019-2831',
    address: '742 Evergreen Terrace, San Francisco, CA',
    designation: 'Chief Technology Officer & Admin',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    joiningDate: '2021-03-15',
    skills: ['System Architecture', 'Java', 'Spring Boot', 'Cloud Native', 'Cybersecurity'],
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 185000,
  },
  {
    id: 'emp-2',
    userId: 'usr-2',
    fullName: 'Sarah Jenkins',
    email: 'hr@enterprise.com',
    phone: '+1 (555) 014-9921',
    address: '1088 Park Avenue, New York, NY',
    designation: 'Senior HR Director',
    departmentId: 'dept-2',
    departmentName: 'Human Resources',
    joiningDate: '2022-01-10',
    skills: ['Talent Acquisition', 'HR Strategy', 'Conflict Resolution', 'Employment Law'],
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 135000,
  },
  {
    id: 'emp-3',
    userId: 'usr-3',
    fullName: 'David K. Miller',
    email: 'employee@enterprise.com',
    phone: '+1 (555) 017-4820',
    address: '450 Mission St, San Francisco, CA',
    designation: 'Senior Java Backend Engineer',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    joiningDate: '2023-06-01',
    skills: ['Java 21', 'Spring Boot 3', 'PostgreSQL', 'Microservices', 'REST APIs', 'Docker'],
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 145000,
  },
  {
    id: 'emp-4',
    userId: 'usr-4',
    fullName: 'Emily Watson',
    email: 'emily.watson@enterprise.com',
    phone: '+1 (555) 012-3344',
    address: '120 Market St, San Jose, CA',
    designation: 'Lead UX Designer',
    departmentId: 'dept-3',
    departmentName: 'Product & Design',
    joiningDate: '2022-08-15',
    skills: ['Figma', 'UI Architecture', 'User Research', 'Design Systems', 'Tailwind CSS'],
    profileImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 130000,
  },
  {
    id: 'emp-5',
    userId: 'usr-5',
    fullName: 'Marcus Brody',
    email: 'marcus.brody@enterprise.com',
    phone: '+1 (555) 018-7711',
    address: '500 Howard St, San Francisco, CA',
    designation: 'Enterprise Sales Manager',
    departmentId: 'dept-4',
    departmentName: 'Sales & Marketing',
    joiningDate: '2023-02-20',
    skills: ['B2B Sales', 'CRM', 'Account Management', 'Negotiation', 'SaaS Growth'],
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 125000,
  },
  {
    id: 'emp-6',
    fullName: 'Victoria Sterling',
    email: 'victoria.sterling@enterprise.com',
    phone: '+1 (555) 011-9822',
    address: '220 Montgomery St, San Francisco, CA',
    designation: 'VP of Finance & Accounting',
    departmentId: 'dept-5',
    departmentName: 'Finance & Legal',
    joiningDate: '2021-11-01',
    skills: ['Corporate Auditing', 'Financial Modeling', 'Risk Analysis', 'Budget Allocation'],
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 160000,
  },
  {
    id: 'emp-7',
    fullName: 'Robert Taylor',
    email: 'robert.taylor@enterprise.com',
    phone: '+1 (555) 013-4490',
    address: '88 First Street, Oakland, CA',
    designation: 'IT Systems Infrastructure Manager',
    departmentId: 'dept-6',
    departmentName: 'Operations & IT',
    joiningDate: '2022-04-12',
    skills: ['Linux Admin', 'Kubernetes', 'Network Security', 'Active Directory', 'AWS'],
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 138000,
  },
  {
    id: 'emp-8',
    fullName: 'Amanda Hayes',
    email: 'amanda.hayes@enterprise.com',
    phone: '+1 (555) 016-3311',
    address: '350 Bush St, San Francisco, CA',
    designation: 'Senior Frontend Developer',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    joiningDate: '2023-09-01',
    skills: ['React 19', 'TypeScript', 'Tailwind CSS', 'Redux', 'Web Performance'],
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 132000,
  },
  {
    id: 'emp-9',
    fullName: 'Carlos Rodriguez',
    email: 'carlos.rodriguez@enterprise.com',
    phone: '+1 (555) 015-8833',
    address: '600 California St, San Francisco, CA',
    designation: 'DevOps & Cloud Architect',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    joiningDate: '2022-10-18',
    skills: ['Docker', 'Terraform', 'CI/CD Pipelines', 'GCP Cloud Run', 'Spring Boot Admin'],
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 148000,
  },
  {
    id: 'emp-10',
    fullName: 'Jessica Chen',
    email: 'jessica.chen@enterprise.com',
    phone: '+1 (555) 018-2299',
    address: '150 Post St, San Francisco, CA',
    designation: 'Talent Acquisition Manager',
    departmentId: 'dept-2',
    departmentName: 'Human Resources',
    joiningDate: '2023-01-15',
    skills: ['Technical Recruiting', 'Interviewing', 'SaaS Onboarding', 'Employer Branding'],
    profileImage: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 115000,
  },
  {
    id: 'emp-11',
    fullName: 'Kevin Patel',
    email: 'kevin.patel@enterprise.com',
    phone: '+1 (555) 014-6677',
    address: '90 Pine St, San Francisco, CA',
    designation: 'Senior Product Manager',
    departmentId: 'dept-3',
    departmentName: 'Product & Design',
    joiningDate: '2022-03-30',
    skills: ['Agile Roadmap', 'Product Analytics', 'User Stories', 'Jira', 'A/B Testing'],
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 142000,
  },
  {
    id: 'emp-12',
    fullName: 'Sophia Martinez',
    email: 'sophia.martinez@enterprise.com',
    phone: '+1 (555) 019-1122',
    address: '400 Sansome St, San Francisco, CA',
    designation: 'Digital Growth & Content Lead',
    departmentId: 'dept-4',
    departmentName: 'Sales & Marketing',
    joiningDate: '2023-05-10',
    skills: ['SEO Strategy', 'Content Marketing', 'HubSpot', 'Google Analytics', 'Copywriting'],
    profileImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    salary: 110000,
  },
];

export const users: User[] = [
  {
    id: 'usr-1',
    username: 'admin',
    email: 'admin@enterprise.com',
    role: 'ADMIN',
    employeeId: 'emp-1',
    createdAt: '2021-03-15T08:00:00.000Z',
  },
  {
    id: 'usr-2',
    username: 'hr_manager',
    email: 'hr@enterprise.com',
    role: 'HR',
    employeeId: 'emp-2',
    createdAt: '2022-01-10T08:00:00.000Z',
  },
  {
    id: 'usr-3',
    username: 'david_engineer',
    email: 'employee@enterprise.com',
    role: 'EMPLOYEE',
    employeeId: 'emp-3',
    createdAt: '2023-06-01T08:00:00.000Z',
  },
  {
    id: 'usr-4',
    username: 'emily_designer',
    email: 'emily.watson@enterprise.com',
    role: 'EMPLOYEE',
    employeeId: 'emp-4',
    createdAt: '2022-08-15T08:00:00.000Z',
  },
  {
    id: 'usr-5',
    username: 'marcus_sales',
    email: 'marcus.brody@enterprise.com',
    role: 'EMPLOYEE',
    employeeId: 'emp-5',
    createdAt: '2023-02-20T08:00:00.000Z',
  },
];

// User Password Database (BCrypt hashes)
export const userPasswords: Map<string, string> = new Map([
  ['usr-1', DEFAULT_PASSWORD_HASH],
  ['usr-2', DEFAULT_PASSWORD_HASH],
  ['usr-3', DEFAULT_PASSWORD_HASH],
  ['usr-4', DEFAULT_PASSWORD_HASH],
  ['usr-5', DEFAULT_PASSWORD_HASH],
]);

// Attendance initial records
const todayStr = new Date().toISOString().split('T')[0];
export const attendanceRecords: Attendance[] = [
  { id: 'att-1', employeeId: 'emp-1', employeeName: 'Alexander Vance', date: todayStr, checkInTime: '08:45 AM', checkOutTime: '05:30 PM', status: 'PRESENT', workHours: 8.75 },
  { id: 'att-2', employeeId: 'emp-2', employeeName: 'Sarah Jenkins', date: todayStr, checkInTime: '09:00 AM', checkOutTime: '05:00 PM', status: 'PRESENT', workHours: 8.0 },
  { id: 'att-3', employeeId: 'emp-3', employeeName: 'David K. Miller', date: todayStr, checkInTime: '09:02 AM', checkOutTime: '05:30 PM', status: 'PRESENT', workHours: 8.5 },
  { id: 'att-4', employeeId: 'emp-4', employeeName: 'Emily Watson', date: todayStr, checkInTime: '09:45 AM', checkOutTime: '06:00 PM', status: 'LATE', workHours: 7.25 },
  { id: 'att-5', employeeId: 'emp-5', employeeName: 'Marcus Brody', date: todayStr, checkInTime: '09:00 AM', checkOutTime: '06:00 PM', status: 'PRESENT', workHours: 9.0 },
  { id: 'att-6', employeeId: 'emp-6', employeeName: 'Victoria Sterling', date: todayStr, checkInTime: '08:50 AM', checkOutTime: '05:15 PM', status: 'PRESENT', workHours: 8.4 },
  { id: 'att-7', employeeId: 'emp-7', employeeName: 'Robert Taylor', date: todayStr, checkInTime: '08:30 AM', checkOutTime: '05:00 PM', status: 'PRESENT', workHours: 8.5 },
  { id: 'att-8', employeeId: 'emp-8', employeeName: 'Amanda Hayes', date: todayStr, checkInTime: '09:10 AM', checkOutTime: '05:40 PM', status: 'PRESENT', workHours: 8.2 },
  { id: 'att-9', employeeId: 'emp-9', employeeName: 'Carlos Rodriguez', date: todayStr, checkInTime: '09:05 AM', checkOutTime: '05:35 PM', status: 'PRESENT', workHours: 8.3 },
  { id: 'att-10', employeeId: 'emp-10', employeeName: 'Jessica Chen', date: todayStr, checkInTime: '09:15 AM', checkOutTime: '05:15 PM', status: 'PRESENT', workHours: 8.0 },
  { id: 'att-11', employeeId: 'emp-11', employeeName: 'Kevin Patel', date: todayStr, checkInTime: '09:50 AM', checkOutTime: '06:15 PM', status: 'LATE', workHours: 7.4 },
  { id: 'att-12', employeeId: 'emp-12', employeeName: 'Sophia Martinez', date: todayStr, checkInTime: '09:00 AM', checkOutTime: '05:00 PM', status: 'PRESENT', workHours: 8.0 },
];

// Leave requests initial records
export const leaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    employeeId: 'emp-3',
    employeeName: 'David K. Miller',
    leaveType: 'ANNUAL',
    startDate: '2026-08-10',
    endDate: '2026-08-14',
    reason: 'Family vacation and personal downtime.',
    status: 'PENDING',
    createdAt: '2026-08-01T10:30:00.000Z',
  },
  {
    id: 'leave-2',
    employeeId: 'emp-4',
    employeeName: 'Emily Watson',
    leaveType: 'SICK',
    startDate: '2026-07-15',
    endDate: '2026-07-16',
    reason: 'Medical checkup and recovery.',
    status: 'APPROVED',
    hrComment: 'Approved by HR. Get well soon!',
    createdAt: '2026-07-14T09:15:00.000Z',
  },
  {
    id: 'leave-3',
    employeeId: 'emp-5',
    employeeName: 'Marcus Brody',
    leaveType: 'CASUAL',
    startDate: '2026-08-05',
    endDate: '2026-08-05',
    reason: 'Attending personal errand.',
    status: 'PENDING',
    createdAt: '2026-08-02T14:20:00.000Z',
  },
  {
    id: 'leave-4',
    employeeId: 'emp-8',
    employeeName: 'Amanda Hayes',
    leaveType: 'CASUAL',
    startDate: '2026-08-18',
    endDate: '2026-08-19',
    reason: 'Family event celebration.',
    status: 'PENDING',
    createdAt: '2026-08-03T09:00:00.000Z',
  },
  {
    id: 'leave-5',
    employeeId: 'emp-11',
    employeeName: 'Kevin Patel',
    leaveType: 'ANNUAL',
    startDate: '2026-09-01',
    endDate: '2026-09-05',
    reason: 'Annual family retreat.',
    status: 'APPROVED',
    hrComment: 'Approved for Q3 leave window.',
    createdAt: '2026-07-28T11:00:00.000Z',
  },
];

// Performance reviews initial records
export const performanceReviews: PerformanceReview[] = [
  {
    id: 'rev-1',
    employeeId: 'emp-3',
    employeeName: 'David K. Miller',
    reviewerId: 'emp-2',
    reviewerName: 'Sarah Jenkins',
    technicalScore: 9,
    communicationScore: 8,
    teamworkScore: 9,
    overallRating: 4.5,
    projectsCompleted: 7,
    feedback: 'David has consistently delivered high-performance Spring Boot microservices with exceptional code quality and test coverage.',
    aiStrengths: [
      'Deep mastery of Java 21 & Spring Boot ecosystem',
      'Strong architectural mindset and clean code principles',
      'Proactive peer code reviewer'
    ],
    aiWeaknesses: [
      'Could document API endpoints more thoroughly in OpenAPI',
      'Opportunity to lead cross-department technical workshops'
    ],
    aiImprovementPlan: '1. Complete AWS Certified Solutions Architect exam by Q4.\n2. Conduct bi-weekly brownbag tech talks on microservice resilient patterns.',
    aiCareerSuggestions: 'Prepared for promotion to Staff Engineer or Technical Lead role within 6-12 months.',
    reviewDate: '2026-06-30',
  },
  {
    id: 'rev-2',
    employeeId: 'emp-4',
    employeeName: 'Emily Watson',
    reviewerId: 'emp-2',
    reviewerName: 'Sarah Jenkins',
    technicalScore: 8,
    communicationScore: 9,
    teamworkScore: 9,
    overallRating: 4.3,
    projectsCompleted: 5,
    feedback: 'Emily modernized our SaaS design system with incredible user feedback metrics.',
    aiStrengths: ['Outstanding empathetic design', 'Cross-functional communication excellence'],
    aiWeaknesses: ['Occasional scope creep on initial prototypes'],
    aiImprovementPlan: 'Set strict phase-1 scope boundaries during design sprint kickoffs.',
    aiCareerSuggestions: 'Track toward UX Director position as department expands.',
    reviewDate: '2026-06-15',
  },
  {
    id: 'rev-3',
    employeeId: 'emp-8',
    employeeName: 'Amanda Hayes',
    reviewerId: 'emp-1',
    reviewerName: 'Alexander Vance',
    technicalScore: 9,
    communicationScore: 9,
    teamworkScore: 10,
    overallRating: 4.7,
    projectsCompleted: 8,
    feedback: 'Amanda transformed frontend rendering speed by 40% and pioneered reusable UI modules.',
    aiStrengths: ['React 19 expert', 'Excellent cross-team mentoring'],
    aiWeaknesses: ['High velocity sometimes outpaces QA testing cycles'],
    aiImprovementPlan: 'Integrate automated E2E Cypress tests before staging merges.',
    aiCareerSuggestions: 'Ready for Lead Frontend Architect path.',
    reviewDate: '2026-07-10',
  },
  {
    id: 'rev-4',
    employeeId: 'emp-9',
    employeeName: 'Carlos Rodriguez',
    reviewerId: 'emp-1',
    reviewerName: 'Alexander Vance',
    technicalScore: 10,
    communicationScore: 8,
    teamworkScore: 9,
    overallRating: 4.6,
    projectsCompleted: 9,
    feedback: 'Carlos built our zero-downtime Cloud Run CI/CD pipeline and reduced hosting costs.',
    aiStrengths: ['GCP Cloud Native infrastructure master', 'Rapid incident resolution'],
    aiWeaknesses: ['Needs to delegate minor ops tickets'],
    aiImprovementPlan: 'Train junior SRE engineers on incident response runbooks.',
    aiCareerSuggestions: 'Promote to Principal DevOps Engineer.',
    reviewDate: '2026-07-20',
  },
];
